function [x, P, Q] = initialize_kf(settings)

if nargin < 1
    settings = set_defaults();
end

%% Initial state, covariance, and system noise

% State: [x, y, tht, vel, omega, imubias]'
x = zeros(6,1);
P = diag([settings.cov.x,...
    settings.cov.y,...
    settings.cov.tht,...
    settings.cov.vel,...
    settings.cov.omg,...
    settings.cov.imubias]);
Q = diag([settings.sys.x^2,...
    settings.sys.y^2,...
    settings.sys.tht^2,...
    settings.sys.vel^2,...
    settings.sys.omg^2,...
    settings.sys.imubias^2]);